export const boxData = [
    {
        Img: "/Images/ListPage/place.png",
        mainTitle: "Great Northern Hotel, a Tribute Portfolio Hotel, London",
        smallTitle: "Westminster Borough, London",
        roomName: "King Room",
        roomDesc: "1 extra-large double bed",
        bottomTitle: "Free cancellation",
        bottomDesc: "You can cancel later, so lock in this great price today.",
        catyOne: "Breakfast",
        catyTwo: "Wifi",
        catyThree: "Spa",
        catyFour: "Bar"
    },
    {
        Img: "/Images/ListPage/place.png",
        mainTitle: "Great Northern Hotel, a Tribute Portfolio Hotel, London",
        smallTitle: "Westminster Borough, London",
        roomName: "King Room",
        roomDesc: "1 extra-large double bed",
        bottomTitle: "Free cancellation",
        bottomDesc: "You can cancel later, so lock in this great price today.",
        catyOne: "Breakfast",
        catyTwo: "Wifi",
        catyThree: "Spa",
        catyFour: "Bar"
    },
    {
        Img: "/Images/ListPage/place.png",
        mainTitle: "Great Northern Hotel, a Tribute Portfolio Hotel, London",
        smallTitle: "Westminster Borough, London",
        roomName: "King Room",
        roomDesc: "1 extra-large double bed",
        bottomTitle: "Free cancellation",
        bottomDesc: "You can cancel later, so lock in this great price today.",
        catyOne: "Breakfast",
        catyTwo: "Wifi",
        catyThree: "Spa",
        catyFour: "Bar"
    },
    {
        Img: "/Images/ListPage/place.png",
        mainTitle: "Great Northern Hotel, a Tribute Portfolio Hotel, London",
        smallTitle: "Westminster Borough, London",
        roomName: "King Room",
        roomDesc: "1 extra-large double bed",
        bottomTitle: "Free cancellation",
        bottomDesc: "You can cancel later, so lock in this great price today.",
        catyOne: "Breakfast",
        catyTwo: "Wifi",
        catyThree: "Spa",
        catyFour: "Bar"
    },
    {
        Img: "/Images/ListPage/place.png",
        mainTitle: "Great Northern Hotel, a Tribute Portfolio Hotel, London",
        smallTitle: "Westminster Borough, London",
        roomName: "King Room",
        roomDesc: "1 extra-large double bed",
        bottomTitle: "Free cancellation",
        bottomDesc: "You can cancel later, so lock in this great price today.",
        catyOne: "Breakfast",
        catyTwo: "Wifi",
        catyThree: "Spa",
        catyFour: "Bar"
    },
    {
        Img: "/Images/ListPage/place.png",
        mainTitle: "Great Northern Hotel, a Tribute Portfolio Hotel, London",
        smallTitle: "Westminster Borough, London",
        roomName: "King Room",
        roomDesc: "1 extra-large double bed",
        bottomTitle: "Free cancellation",
        bottomDesc: "You can cancel later, so lock in this great price today.",
        catyOne: "Breakfast",
        catyTwo: "Wifi",
        catyThree: "Spa",
        catyFour: "Bar"
    },
    {
        Img: "/Images/ListPage/place.png",
        mainTitle: "Great Northern Hotel, a Tribute Portfolio Hotel, London",
        smallTitle: "Westminster Borough, London",
        roomName: "King Room",
        roomDesc: "1 extra-large double bed",
        bottomTitle: "Free cancellation",
        bottomDesc: "You can cancel later, so lock in this great price today.",
        catyOne: "Breakfast",
        catyTwo: "Wifi",
        catyThree: "Spa",
        catyFour: "Bar"
    },
]